/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Campamento;
import diputacionalava.Main;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author iBaD
 */
public class CrearCampamento extends javax.swing.JFrame {

    private int opcion;
    private Campamento c;
    public CrearCampamento() {
        initComponents();
        setLocationRelativeTo(null);
        NoNombre.setVisible(false);
        NoLugar.setVisible(false);
        NoFechaI.setVisible(false);
        NoFechaF.setVisible(false);
        NoEdadMin.setVisible(false);
        NoEdadMax.setVisible(false);
        NoCapacidad.setVisible(false);
        eID.setVisible(false);
        tID.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        tLugar = new javax.swing.JTextField();
        tEdadMin = new javax.swing.JTextField();
        tEdadMax = new javax.swing.JTextField();
        tFechaF = new javax.swing.JTextField();
        tFechaI = new javax.swing.JTextField();
        tCapacidad = new javax.swing.JTextField();
        AceptarModificar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        NoFechaI = new javax.swing.JLabel();
        NoNombre = new javax.swing.JLabel();
        NoFechaF = new javax.swing.JLabel();
        NoEdadMin = new javax.swing.JLabel();
        NoCapacidad = new javax.swing.JLabel();
        NoLugar = new javax.swing.JLabel();
        NoEdadMax = new javax.swing.JLabel();
        eID = new javax.swing.JLabel();
        tID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Crear Campamento");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Fecha fin:");

        jLabel4.setText("Edad mínima:");

        jLabel5.setText("Lugar:");

        jLabel6.setText("Fecha inicio:");

        jLabel7.setText("Edad máxima:");

        jLabel8.setText("Capacidad:");

        AceptarModificar.setText("Aceptar y crear");
        AceptarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarModificarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        NoFechaI.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoFechaI.setForeground(new java.awt.Color(255, 0, 0));
        NoFechaI.setText("*Fecha no válida (dd/mm/aaaa)");

        NoNombre.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoNombre.setForeground(new java.awt.Color(255, 0, 0));
        NoNombre.setText("*Nombre no válido");

        NoFechaF.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoFechaF.setForeground(new java.awt.Color(255, 0, 0));
        NoFechaF.setText("*Fecha no válida (dd/mm/aaaa)");

        NoEdadMin.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoEdadMin.setForeground(new java.awt.Color(255, 0, 0));
        NoEdadMin.setText("*Edad no válida");

        NoCapacidad.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoCapacidad.setForeground(new java.awt.Color(255, 0, 0));
        NoCapacidad.setText("*Capacidad no válida");

        NoLugar.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoLugar.setForeground(new java.awt.Color(255, 0, 0));
        NoLugar.setText("*Lugar no válido");

        NoEdadMax.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoEdadMax.setForeground(new java.awt.Color(255, 0, 0));
        NoEdadMax.setText("*Edad no válida");

        eID.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NoFechaF))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NoLugar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(61, 61, 61)
                                    .addComponent(jLabel1)
                                    .addGap(36, 36, 36)
                                    .addComponent(eID)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NoNombre)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tCapacidad))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tEdadMin))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tEdadMax, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(NoCapacidad))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NoEdadMin)
                                            .addComponent(NoEdadMax)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NoFechaI)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AceptarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eID)
                            .addComponent(tID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(NoLugar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(NoFechaI))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(NoFechaF))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tEdadMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoEdadMin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tEdadMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(NoEdadMax))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoCapacidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(opcion==0){
            Main.CerrarCrearCampamento(0);
        }else if(opcion==1){
            Main.CerrarCrearCampamento(1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AceptarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarModificarActionPerformed
        if(opcion==0){
            try {
                if(CrearCampamento(0)){
                   Main.InsertarNuevoCampamento(c);
                   JOptionPane.showMessageDialog(this,"Campamento creado con éxito"); 
                }
            } catch (Exception e) {
                System.out.println("Ha ocurrido un error"+e.getMessage());
            }
        }else if(opcion==1){
            try {
                if(CrearCampamento(1) && JOptionPane.showConfirmDialog(this, "¿Estás seguro de querer modificar este campamento?")==0){
                    Main.ModificarTablaCampamentos(c);
                    JOptionPane.showMessageDialog(this,"Campamento modificado con éxito");
                }
            } catch (Exception e) {
                System.out.println("Ha ocurrido un error"+e.getMessage());
            }
        }
    }//GEN-LAST:event_AceptarModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCampamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCampamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCampamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCampamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCampamento().setVisible(true);
            }
        });
    }
    
    public void Crear(){
        opcion=0;
    }
    
    public void Modificar(Campamento c){
        opcion=1;
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        eID.setVisible(true);
        tID.setVisible(true);
        tID.setText(String.valueOf(c.getId()));
        tID.setEnabled(false);
        AceptarModificar.setText("Aceptar y modificar");
        tNombre.setText(c.getNombre());
        tNombre.setEnabled(false);
        tLugar.setText(c.getLugar());
        tFechaI.setText(String.valueOf(c.getFechaI().format(formato)));
        tFechaF.setText(String.valueOf(c.getFechaF().format(formato)));
        tEdadMin.setText(String.valueOf(c.getEdadMin()));
        tEdadMax.setText(String.valueOf(c.getEdadMax()));
        tCapacidad.setText(String.valueOf(c.getCapacidad()));
    }
    
    public boolean CrearCampamento(int o){
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        if(!ValidarNombre()){
            NoNombre.setVisible(true);
            return false;
        }else{
            NoNombre.setVisible(false);
            if(!ValidarLugar()){
                NoLugar.setVisible(true);
                return false;
            }else{
                NoLugar.setVisible(false);
                if(!ValidarFecha(formato,tFechaI.getText(),0)){
                    NoFechaI.setVisible(true);
                    return false;
                }else{
                    NoFechaI.setVisible(false);
                    if(!ValidarFecha(formato,tFechaF.getText(),1)){
                        NoFechaF.setVisible(true);
                        return false;
                    }else{
                        NoFechaF.setVisible(false);
                        if(!ValidarEdad(0,tEdadMin.getText())){
                            NoEdadMin.setVisible(true);
                            return false;
                        }else{
                            NoEdadMin.setVisible(false);
                            if(!ValidarEdad(1,tEdadMax.getText())){
                                NoEdadMax.setVisible(true);
                                return false;
                            }else{
                                NoEdadMax.setVisible(false);
                                if(!ValidarCapacidad()){
                                    NoCapacidad.setVisible(true);
                                    return false;
                                }else{
                                    NoCapacidad.setVisible(false);
                                    LocalDate fechaI = LocalDate.parse(tFechaI.getText(), formato);
                                    LocalDate fechaF = LocalDate.parse(tFechaF.getText(), formato);
                                    c = new Campamento(tNombre.getText(),tLugar.getText(),fechaI,fechaF,Integer.parseInt(tEdadMin.getText())
                                                       ,Integer.parseInt(tEdadMax.getText()),Integer.parseInt(tCapacidad.getText()));
                                    if(o==1){
                                        c.setId(Integer.parseInt(tID.getText()));
                                    }
                                    return true;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    
    public boolean ValidarNombre(){
        Pattern p = Pattern.compile("^[A-z 0-9]{1,30}$");
         Matcher m = p.matcher(tNombre.getText());
         if(m.matches()){
             return true;
         }
         else{
             return false;
         } 
    }
    
    public boolean ValidarLugar(){
        if(tLugar.getText().isEmpty()){
            return false;
        }else{
            return true;
        }
    }
    
    public boolean ValidarFecha(DateTimeFormatter formato,String fechaString,int opcion){
        try{
            LocalDate fecha = LocalDate.parse(fechaString,formato);
            if(fecha.isBefore(LocalDate.now())){
                if(opcion==1){
                   NoFechaF.setText("*Fecha pasada");
               }else{
                   NoFechaI.setText("*Fecha pasada");
               }
                return false;
            }else{
                if(opcion==1){
                    LocalDate fechaI = LocalDate.parse(tFechaI.getText(),formato);
                    if(fecha.isBefore(fechaI)){
                        NoFechaF.setText("*Fecha fin anterior a fecha inicio");
                        return false;
                    }else{
                        return true;
                    }
                }
                return true;
            }
        }catch(java.time.format.DateTimeParseException e){
            if(opcion==1){
                   NoFechaF.setText("*Fecha no válida (dd/mm/aaaa)");
               }else{
                   NoFechaI.setText("*Fecha no válida (dd/mm/aaaa)");
               }
            return false;
        }
    }
    
    public boolean ValidarEdad(int opcion,String edadS){
        try{
           int edad = Integer.parseInt(edadS);
           if(edad<=0){
               if(opcion==1){
                   NoEdadMax.setText("*Edad <= 0");
               }else{
                   NoEdadMin.setText("*Edad <= 0");
               }
               return false;
           }else{
               if(opcion==1){
                   int edadMin = Integer.parseInt(tEdadMin.getText());
                   if(edad<edadMin){
                       NoEdadMax.setText("*Edad máxima < Edad mínima");
                       return false;
                   }else{
                       return true;
                   }
               }
               return true;
           }
        }catch(NumberFormatException e){
            if(opcion==1){
                   NoEdadMax.setText("*Edad no válida");
               }else{
                NoEdadMin.setText("*Edad no válida");
            }
            return false;
        }
    }
    
    public boolean ValidarCapacidad(){
       try{
           int capacidad = Integer.parseInt(tCapacidad.getText());
           if(capacidad<=0){
               return false;
           }
           return true;
       }catch(NumberFormatException e){
           return false;
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarModificar;
    private javax.swing.JLabel NoCapacidad;
    private javax.swing.JLabel NoEdadMax;
    private javax.swing.JLabel NoEdadMin;
    private javax.swing.JLabel NoFechaF;
    private javax.swing.JLabel NoFechaI;
    private javax.swing.JLabel NoLugar;
    private javax.swing.JLabel NoNombre;
    private javax.swing.JLabel eID;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tCapacidad;
    private javax.swing.JTextField tEdadMax;
    private javax.swing.JTextField tEdadMin;
    private javax.swing.JTextField tFechaF;
    private javax.swing.JTextField tFechaI;
    private javax.swing.JTextField tID;
    private javax.swing.JTextField tLugar;
    private javax.swing.JTextField tNombre;
    // End of variables declaration//GEN-END:variables
}
