/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Campamento;
import Clases.Persona;
import diputacionalava.Main;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author iBaD
 */
public class InscribirPersona extends javax.swing.JFrame {
    Persona per = new Persona();
    Campamento camp;
    DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    public InscribirPersona() {
        initComponents();
        setLocationRelativeTo(null);
        NoNombre.setVisible(false);
        NoApellido1.setVisible(false);
        NoApellido2.setVisible(false);
        NoFecha.setVisible(false);
        NoTelefono.setVisible(false);
        NoEmail.setVisible(false);
        NoDireccion.setVisible(false);
        eID.setVisible(false);
        tID.setVisible(false);
        ePE.setVisible(false);
        try {
             Main.RellenarComboCamp(cbNombre);
        } catch (Exception e) {
                System.out.println("ha ocurrido un error "+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbNombre = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tFechaI = new javax.swing.JTextField();
        eLugar = new javax.swing.JLabel();
        tLugar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tEdadMin = new javax.swing.JTextField();
        tEdadMax = new javax.swing.JTextField();
        Inscribir = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        NoNombre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NoApellido1 = new javax.swing.JLabel();
        tApellido1 = new javax.swing.JTextField();
        tFechaNac = new javax.swing.JTextField();
        eApellido2 = new javax.swing.JLabel();
        NoApellido2 = new javax.swing.JLabel();
        tApellido2 = new javax.swing.JTextField();
        NoFecha = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        tTelefono = new javax.swing.JTextField();
        NoTelefono = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        NoEmail = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tDireccion = new javax.swing.JTextField();
        NoDireccion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        eID = new javax.swing.JLabel();
        tID = new javax.swing.JTextField();
        ePE = new javax.swing.JLabel();
        ReiniciarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Inscribir persona");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Campamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        jLabel2.setText("Nombre:");

        cbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha Inicio:");

        tFechaI.setEnabled(false);

        eLugar.setText("Lugar:");

        tLugar.setEnabled(false);

        jLabel4.setText("Edad mínima:");

        jLabel5.setText("Edad máxima:");

        tEdadMin.setEnabled(false);

        tEdadMax.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(eLugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tEdadMin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tEdadMax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eLugar)
                    .addComponent(tLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(tEdadMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tEdadMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        Inscribir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Inscribir.setText("Inscribir");
        Inscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscribirActionPerformed(evt);
            }
        });

        Cancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        NoNombre.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoNombre.setForeground(new java.awt.Color(255, 0, 0));
        NoNombre.setText("*Nombre no válido");

        jLabel6.setText("Nombre:");

        tNombre.setEnabled(false);

        jLabel7.setText("Primer apellido:");

        NoApellido1.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoApellido1.setForeground(new java.awt.Color(255, 0, 0));
        NoApellido1.setText("*Apellido no válido");

        tApellido1.setEnabled(false);

        tFechaNac.setEnabled(false);

        eApellido2.setText("Segundo apellido:");

        NoApellido2.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoApellido2.setForeground(new java.awt.Color(255, 0, 0));
        NoApellido2.setText("*Apellido no válido");

        tApellido2.setEnabled(false);

        NoFecha.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoFecha.setForeground(new java.awt.Color(255, 0, 0));
        NoFecha.setText("*Fecha no válida");

        jLabel8.setText("Fecha nacimiento:");

        Buscar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        tTelefono.setEnabled(false);

        NoTelefono.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoTelefono.setForeground(new java.awt.Color(255, 0, 0));
        NoTelefono.setText("*Teléfono no válido");

        jLabel10.setText("Email:");

        tEmail.setEnabled(false);

        NoEmail.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoEmail.setForeground(new java.awt.Color(255, 0, 0));
        NoEmail.setText("*Email no válido");

        jLabel11.setText("Dirección:");

        tDireccion.setEnabled(false);

        NoDireccion.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoDireccion.setForeground(new java.awt.Color(255, 0, 0));
        NoDireccion.setText("*Dirección no válida (c/ calle portal piso)");

        jLabel9.setText("Teléfono:");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setText("Persona");

        eID.setText("ID:");

        ePE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ePE.setText("Persona encontrada");

        ReiniciarDatos.setText("Reiniciar Datos");
        ReiniciarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(206, 206, 206))
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel12)
                .addGap(103, 103, 103)
                .addComponent(eID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tID, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Inscribir)
                                        .addGap(131, 131, 131)
                                        .addComponent(Cancelar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NoDireccion))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                    .addComponent(tTelefono))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NoEmail)
                                    .addComponent(NoTelefono, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tNombre)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NoNombre)
                                    .addComponent(NoApellido1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eApellido2)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(tFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NoFecha)
                                    .addComponent(NoApellido2))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Buscar)
                        .addGap(18, 18, 18)
                        .addComponent(ePE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ReiniciarDatos)
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(eID)
                    .addComponent(tID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoApellido1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eApellido2)
                    .addComponent(tApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoApellido2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoFecha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscar)
                    .addComponent(ePE)
                    .addComponent(ReiniciarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoTelefono))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoDireccion))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inscribir)
                    .addComponent(Cancelar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNombreActionPerformed
        String nombre = cbNombre.getSelectedItem().toString();
        if(nombre.equals("-----Elegir campamento-----")){
            LimpiarCampos();
            Inscribir.setEnabled(false);
            InhabilitarPartePersona();
        }else{
             camp = new Campamento();
            camp = Main.ExtraerDatosCampamento(nombre);
            AutocompletarDatos();
            Inscribir.setEnabled(true);
            HabilitarPartePersona();
        }
    }//GEN-LAST:event_cbNombreActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        if(Validar4PrimerosDatos()){
            LocalDate fecha = LocalDate.parse(tFechaNac.getText(), formatoFecha);
             per = new Persona(tNombre.getText(),tApellido1.getText(),tApellido2.getText(),fecha);
            try {
                Main.BuscarPersona(per,0);
            } catch (Exception ex) {
                System.out.println("Ha ocurrido un problema al buscar a la persona "+ ex.getMessage());
            }
        }else{
            eID.setVisible(false);
            tID.setVisible(false);
            ePE.setVisible(false);
            tTelefono.setEnabled(false);
            tEmail.setEnabled(false);
            tDireccion.setEnabled(false);
        }
        
    }//GEN-LAST:event_BuscarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        Main.CerrarInscribir();
    }//GEN-LAST:event_CancelarActionPerformed

    private void InscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscribirActionPerformed
        if(!tID.isVisible()){
            if(ValidarRestoDeDatos()){
                per.setDireccion(tDireccion.getText());
                per.setEmail(tEmail.getText());
                per.setTelefono(tTelefono.getText());
                try{
                    Main.InsertarNuevaPersona(per);
                    JOptionPane.showMessageDialog(null, "Persona añadida con éxito");
                    int codigo = Main.ObtenerCodigoPersona(per);
                    per.setId(codigo);
                }catch(Exception e){
                    System.out.println("Ha ocurrido un error al insertar a la persona "+e.getMessage());
                }
                InsertarPersonaEnCamp();
            }
        }else{
              InsertarPersonaEnCamp(); 
           }
        
        
        
    }//GEN-LAST:event_InscribirActionPerformed

    private void ReiniciarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarDatosActionPerformed
            ReiniciarDatos();
    }//GEN-LAST:event_ReiniciarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscribirPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscribirPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscribirPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscribirPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscribirPersona().setVisible(true);
            }
        });
    }
    
    public void LimpiarCampos(){
        tFechaI.setText("");
        tLugar.setText("");
        tEdadMin.setText("");
        tEdadMax.setText("");
    }
    
    public void InhabilitarPartePersona(){
        ReiniciarDatos();
        tNombre.setEnabled(false);
        tApellido1.setEnabled(false);
        tApellido2.setEnabled(false);
        tFechaNac.setEnabled(false);
        Buscar.setEnabled(false);
        ReiniciarDatos.setEnabled(false);
    }
    
    public void HabilitarPartePersona(){
        tNombre.setEnabled(true);
        tApellido1.setEnabled(true);
        tApellido2.setEnabled(true);
        tFechaNac.setEnabled(true);
        Buscar.setEnabled(true);
        ReiniciarDatos.setEnabled(true);
    }
    
    public void AutocompletarDatos(){
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        tFechaI.setText(camp.getFechaI().format(formato));
        tLugar.setText(camp.getLugar());
        tEdadMin.setText(String.valueOf(camp.getEdadMin()));
        tEdadMax.setText(String.valueOf(camp.getEdadMax()));
    }
    
    public boolean Validar4PrimerosDatos(){
        if(!ValidarNombre()){
            NoNombre.setVisible(true);
            return false;
        }else{
            NoNombre.setVisible(false);
            if(!ValidarApellido(tApellido1.getText())){
                NoApellido1.setVisible(true);
                return false;
            }else{
                NoApellido1.setVisible(false);
                if(!ValidarApellido(tApellido2.getText())){
                    NoApellido2.setVisible(true);
                    return false;
                }else{
                    NoApellido2.setVisible(false);
                    if(!ValidarFecha(tFechaNac.getText())){
                        NoFecha.setVisible(true);
                        return false;
                    }else{
                        NoFecha.setVisible(false);
                        return true;
                    }
                }
            }
        }
    }
    
    public boolean ValidarNombre(){
        Pattern p = Pattern.compile("^[A-z]{2}([ ]?[A-z]*)*$");
         Matcher m = p.matcher(tNombre.getText());
         if(m.matches()){
             return true;
         }
         else{
             return false;
         } 
    }
    
    public boolean ValidarApellido(String apellido){
        Pattern p = Pattern.compile("^[A-z]{2,4}([ ]?[A-z]*)*$");
         Matcher m = p.matcher(apellido);
         if(m.matches()){
             return true;
         }
         else{
             return false;
         } 
    }
    
    public boolean ValidarFecha(String fechaS){
        try{
            LocalDate fecha = LocalDate.parse(fechaS,formatoFecha);
            if(fecha.isAfter(LocalDate.now())){
                NoFecha.setText("*Fecha futura");
                return false;
            }else{
                if(!ComprobarEdadParaEntrar()){
                    NoFecha.setText("*No comprendido entre el rango de edad de este campamento");
                    return false;
                }else{
                    return true;
                }
            }
        }catch(java.time.format.DateTimeParseException e){
            NoFecha.setText("*Fecha no válida (dd/mm/aaaa)");
            return false;
        }
        
    }
    
    public void PersonaNoEncontrada(){
        if(JOptionPane.showConfirmDialog(this, "Persona no encontrada\n\n¿Añadir a esta persona?\n")==0){
            tNombre.setEnabled(false);
            tApellido1.setEnabled(false);
            tApellido2.setEnabled(false);
            tFechaNac.setEnabled(false);
            tTelefono.setEnabled(true);
            tEmail.setEnabled(true);
            tDireccion.setEnabled(true);
            eID.setVisible(false);
            tID.setVisible(false);
            tTelefono.setText("");
            tDireccion.setText("");
            tEmail.setText("");
            ePE.setVisible(false);
        }
        
    }
    
    public void PersonaEncontrada(Persona pe){
        per = pe;
        if(Main.ComprobarNumeroDeCampamentosPersona(per.getId())){
            tTelefono.setEnabled(false);
            tEmail.setEnabled(false);
            tDireccion.setEnabled(false);
            tNombre.setEnabled(false);
            tApellido1.setEnabled(false);
            tApellido2.setEnabled(false);
            tFechaNac.setEnabled(false);
            Buscar.setEnabled(false);
            tID.setEnabled(false);
            eID.setVisible(true);
            tID.setVisible(true);
            tID.setText(String.valueOf(pe.getId()));
            tTelefono.setText(pe.getTelefono());
            tDireccion.setText(pe.getTelefono());
            tEmail.setText(pe.getEmail());
            ePE.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Esta persona ya está inscrita en 3 campamentos");
        }
        
    }
    
    public boolean ComprobarEdadParaEntrar(){
        LocalDate nac = LocalDate.parse(tFechaNac.getText(),formatoFecha);
        LocalDate hoy = LocalDate.now();
        Period periodo = Period.between(nac, hoy);
        if (periodo.getYears() >= Integer.parseInt(tEdadMin.getText()) && periodo.getYears() <= Integer.parseInt(tEdadMax.getText())){
            return true;
        }else{
            return false;
        }

    }
    
    public boolean ValidarRestoDeDatos(){
        if(!ValidarTelefono()){
            NoTelefono.setVisible(true);
            return false;
        }else{
            NoTelefono.setVisible(false);
            if(!ValidarEmail()){
                NoEmail.setVisible(true);
                return false;
            }else{
                NoEmail.setVisible(false);
                if(!ValidarDireccion()){
                    NoDireccion.setVisible(true);
                    return false;
                }else{
                    NoDireccion.setVisible(false);
                    return true;
                }
            }
        }
    }
    
    public boolean ValidarTelefono(){
        Pattern p = Pattern.compile("^[6|7|9][0-9]{8}$");
         Matcher m = p.matcher(tTelefono.getText());
         if(m.matches()){
             return true;
         }
         else{
             return false;
         } 
    }
    
    public boolean ValidarEmail(){
        Pattern p = Pattern.compile("^[_A-z0-9-]+(.[_A-z0-9-]+)*@[A-z0-9-]+(\\.[A-z0-9]+)*(\\.[A-z]{2,4})$");
         Matcher m = p.matcher(tEmail.getText());
         if(m.matches()){
             return true;
         }
         else{
             return false;
         } 
    }
    
    public boolean ValidarDireccion(){
        Pattern p = Pattern.compile("^[cC]/[ ]?[A-z]+([ ][A-z]+)*[ ][0-9]{1,3}[ ](([0-9]+|[pP][bB])[Aa|Bb|Cc|Dd|Ii|Ee|Ff])$");
         Matcher m = p.matcher(tDireccion.getText());
         if(m.matches()){
             return true;
         }
         else{
             return false;
         } 
    }
    
    public void InsertarPersonaEnCamp(){
        try{
          Main.InsertarPerEnCamp(per,camp);
          JOptionPane.showMessageDialog(null, "Se ha inscrito a "+per.getNombre()+" "+per.getApellido1()+" "+per.getApellido2()+" en "+camp.getNombre()+" exitosamente");
        }catch(com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException e){
            JOptionPane.showMessageDialog(this, "Persona ya inscrita en este campamento");
            ReiniciarDatos();
        }
        catch(Exception e){
            System.out.println("Ha ocurrido un error al añadir esta persona al campamento "+e.getMessage());
        } 
    }
    
    public void ReiniciarDatos(){
            Buscar.setEnabled(true);
            eID.setVisible(false);
            tID.setVisible(false);
            ePE.setVisible(false);
            tTelefono.setEnabled(false);
            tEmail.setEnabled(false);
            tDireccion.setEnabled(false);
            tNombre.setEnabled(true);
            tApellido1.setEnabled(true);
            tApellido2.setEnabled(true);
            tFechaNac.setEnabled(true);
            tNombre.setText("");
            tApellido1.setText("");
            tApellido2.setText("");
            tFechaNac.setText("");
            tTelefono.setText("");
            tDireccion.setText("");
            tEmail.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Inscribir;
    private javax.swing.JLabel NoApellido1;
    private javax.swing.JLabel NoApellido2;
    private javax.swing.JLabel NoDireccion;
    private javax.swing.JLabel NoEmail;
    private javax.swing.JLabel NoFecha;
    private javax.swing.JLabel NoNombre;
    private javax.swing.JLabel NoTelefono;
    private javax.swing.JButton ReiniciarDatos;
    private javax.swing.JComboBox<String> cbNombre;
    private javax.swing.JLabel eApellido2;
    private javax.swing.JLabel eID;
    private javax.swing.JLabel eLugar;
    private javax.swing.JLabel ePE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tApellido1;
    private javax.swing.JTextField tApellido2;
    private javax.swing.JTextField tDireccion;
    private javax.swing.JTextField tEdadMax;
    private javax.swing.JTextField tEdadMin;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tFechaI;
    private javax.swing.JTextField tFechaNac;
    private javax.swing.JTextField tID;
    private javax.swing.JTextField tLugar;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tTelefono;
    // End of variables declaration//GEN-END:variables
}
