/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Usuario;
import diputacionalava.Main;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author iBaD
 */
public class RegistrarUsuario extends javax.swing.JFrame {

    Usuario u = new Usuario();
    public RegistrarUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        NoUsuario1.setVisible(false);
        NoUsuario2.setVisible(false);
        NoPass1.setVisible(false);
        NoPass2.setVisible(false);
        //TO DO VALIDACIONES DE REGISTRO DE NUEVO USUARIO , POSIBLE IMPLEMENTAR DAR PERMISO ADMIN A OTRO USUARIO
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tUsuario1 = new javax.swing.JTextField();
        tUsuario2 = new javax.swing.JTextField();
        tPass1 = new javax.swing.JPasswordField();
        tPass2 = new javax.swing.JPasswordField();
        NoUsuario1 = new javax.swing.JLabel();
        NoUsuario2 = new javax.swing.JLabel();
        NoPass1 = new javax.swing.JLabel();
        NoPass2 = new javax.swing.JLabel();
        Registrar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        ckAdmin = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Nuevo Usuario");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Confirmar Usuario:");

        jLabel4.setText("Contraseña:");

        jLabel5.setText("Confirmar Contraseña:");

        NoUsuario1.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoUsuario1.setForeground(new java.awt.Color(255, 0, 0));
        NoUsuario1.setText("*Inválido formato (AAA1111AA)");

        NoUsuario2.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoUsuario2.setForeground(new java.awt.Color(255, 0, 0));
        NoUsuario2.setText("*No coincide con el primero");

        NoPass1.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoPass1.setForeground(new java.awt.Color(255, 0, 0));
        NoPass1.setText("*Inválida , 8 caractéres mínimo");

        NoPass2.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoPass2.setForeground(new java.awt.Color(255, 0, 0));
        NoPass2.setText("*No coincide con la primero");

        Registrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        Cancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        ckAdmin.setText("Permiso de administrador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(Registrar)
                        .addGap(65, 65, 65)
                        .addComponent(Cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckAdmin)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tPass2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tPass1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tUsuario2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NoUsuario1)
                                    .addComponent(NoUsuario2)
                                    .addComponent(NoPass2)
                                    .addComponent(NoPass1))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoUsuario1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoUsuario2))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoPass1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoPass2))
                .addGap(37, 37, 37)
                .addComponent(ckAdmin)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registrar)
                    .addComponent(Cancelar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
       Main.CerrarRegistrarUsuario();
    }//GEN-LAST:event_CancelarActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        NoUsuario1.setVisible(false);
        NoUsuario2.setVisible(false);
        NoPass1.setVisible(false);
        NoPass2.setVisible(false);
        if(ValidarDatos()){
            try{
                Main.InsertarUsuario(u);
                JOptionPane.showMessageDialog(this, "Nuevo usuario creado con éxito");
            }catch(com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException e){
                JOptionPane.showMessageDialog(this, "Este usuario ya existe");
            }
            catch(Exception e){
                System.out.println("Ha ocurrido un error al intentar crear otro usuario"+e.getMessage());
            }
        }
    }//GEN-LAST:event_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUsuario().setVisible(true);
            }
        });
    }
    
    public boolean ValidarDatos(){
        if(!ValidarUsuario()){
            NoUsuario1.setVisible(true);
            return false;
        }else{
            NoUsuario1.setVisible(false);
            if(!ValidarPass()){
                NoPass1.setVisible(true);
                return false;
            }else{
                NoPass1.setVisible(false);
                if(!tUsuario2.getText().equals(tUsuario1.getText())){
                    NoUsuario2.setVisible(true);
                    return false;
                }else{
                    NoUsuario2.setVisible(false);
                    if(!tPass2.getText().equals(tPass1.getText())){
                        NoPass2.setVisible(true);
                        return false;
                    }else{
                        NoPass2.setVisible(false);
                        u.setUsuario(tUsuario1.getText());
                        u.setPass(tPass1.getText());
                        u.setAdmin(ckAdmin.isSelected());
                        return true;
                    }
                }
            }
        }
    }
     
    public boolean ValidarUsuario(){
        Pattern p = Pattern.compile("^[A-z]{3}[0-9]{4}[A-z]{2}$");
         Matcher m = p.matcher(tUsuario1.getText());
         if(m.matches()){
             return true;
         }
         else{
             return false;
         } 
    }
    
    public boolean ValidarPass(){
        Pattern p = Pattern.compile("^[A-z0-9-_.,@]{8,32}$");
         Matcher m = p.matcher(tPass1.getText());
         if(m.matches()){
             return true;
         }
         else{
             return false;
         } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel NoPass1;
    private javax.swing.JLabel NoPass2;
    private javax.swing.JLabel NoUsuario1;
    private javax.swing.JLabel NoUsuario2;
    private javax.swing.JButton Registrar;
    private javax.swing.JCheckBox ckAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField tPass1;
    private javax.swing.JPasswordField tPass2;
    private javax.swing.JTextField tUsuario1;
    private javax.swing.JTextField tUsuario2;
    // End of variables declaration//GEN-END:variables
}
