/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Campamento;
import Clases.Persona;
import diputacionalava.Main;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author iBaD
 */
public class RetirarPersona extends javax.swing.JFrame {
    int opcion;
    Persona pe = new Persona();
    Campamento camp = new Campamento();
    ArrayList<Campamento> campamentos = new ArrayList();
    DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    public RetirarPersona() {
        initComponents();
        setLocationRelativeTo(null);
        NoNombre.setVisible(false);
        NoApellido1.setVisible(false);
        NoApellido2.setVisible(false);
        NoFecha.setVisible(false);
        cbNombre.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        tFechaNac = new javax.swing.JTextField();
        eApellido2 = new javax.swing.JLabel();
        NoApellido2 = new javax.swing.JLabel();
        tApellido2 = new javax.swing.JTextField();
        NoFecha = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NoNombre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NoApellido1 = new javax.swing.JLabel();
        tApellido1 = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        panelCamp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbNombre = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tFechaI = new javax.swing.JTextField();
        eLugar = new javax.swing.JLabel();
        tLugar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tFechaF = new javax.swing.JTextField();
        Cancelar = new javax.swing.JButton();
        Retirar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titulo.setText("Retirar Persona");

        eApellido2.setText("Segundo apellido:");

        NoApellido2.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoApellido2.setForeground(new java.awt.Color(255, 0, 0));
        NoApellido2.setText("*Apellido no válido");

        NoFecha.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoFecha.setForeground(new java.awt.Color(255, 0, 0));
        NoFecha.setText("*Fecha no válida");

        jLabel8.setText("Fecha nacimiento:");

        NoNombre.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoNombre.setForeground(new java.awt.Color(255, 0, 0));
        NoNombre.setText("*Nombre no válido");

        jLabel6.setText("Nombre:");

        jLabel7.setText("Primer apellido:");

        NoApellido1.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        NoApellido1.setForeground(new java.awt.Color(255, 0, 0));
        NoApellido1.setText("*Apellido no válido");

        Buscar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        panelCamp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Campamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N

        jLabel2.setText("Nombre:");

        cbNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNombreItemStateChanged(evt);
            }
        });

        jLabel3.setText("Fecha Inicio:");

        tFechaI.setEnabled(false);

        eLugar.setText("Lugar:");

        tLugar.setEnabled(false);

        jLabel4.setText("Fecha Fin:");

        tFechaF.setEnabled(false);

        javax.swing.GroupLayout panelCampLayout = new javax.swing.GroupLayout(panelCamp);
        panelCamp.setLayout(panelCampLayout);
        panelCampLayout.setHorizontalGroup(
            panelCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCampLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCampLayout.createSequentialGroup()
                        .addComponent(eLugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tLugar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCampLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCampLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tFechaF)))
                .addGap(47, 47, 47))
        );
        panelCampLayout.setVerticalGroup(
            panelCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(panelCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eLugar)
                    .addComponent(tLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        Cancelar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Retirar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Retirar.setText("Retirar");
        Retirar.setEnabled(false);
        Retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Reiniciar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCamp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(titulo)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NoNombre)
                                        .addComponent(NoApellido1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eApellido2)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(tFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NoFecha)
                                    .addComponent(NoApellido2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(Buscar)
                                .addGap(113, 113, 113)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(Retirar)
                        .addGap(117, 117, 117)
                        .addComponent(Cancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoApellido1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eApellido2)
                    .addComponent(tApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoApellido2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar)
                    .addComponent(Retirar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        if(ValidarDatos()){
            LocalDate fecha = LocalDate.parse(tFechaNac.getText(), formatoFecha);
             Persona per = new Persona(tNombre.getText(),tApellido1.getText(),tApellido2.getText(),fecha);
             try {
                Main.BuscarPersona(per,1);
            } catch (Exception ex) {
                System.out.println("Ha ocurrido un problema al buscar a la persona "+ ex.getMessage());
            }
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Main.ResetearVentanaRetirar(opcion);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
       Main.CerrarRetirarPersona();
    }//GEN-LAST:event_CancelarActionPerformed

    private void cbNombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNombreItemStateChanged
        String nombre = cbNombre.getSelectedItem().toString();
            int x;
            for(x=0;x<campamentos.size()&&!campamentos.get(x).getNombre().equals(nombre);x++){}
            camp = campamentos.get(x);
            tFechaI.setText(campamentos.get(x).getFechaI().toString());
            tFechaF.setText(campamentos.get(x).getFechaF().toString());
            tLugar.setText(campamentos.get(x).getLugar());
        
    }//GEN-LAST:event_cbNombreItemStateChanged

    private void RetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirarActionPerformed
        if(JOptionPane.showConfirmDialog(this, "¿Estás seguro de retirar a "+tNombre.getText()+" de "+cbNombre.getSelectedItem().toString()+"?")==0){
            try{
              Main.RetirarPersonaDeCampamento(camp.getId(),pe.getId()); 
            }catch(Exception e){
                System.out.println("Ha ocurrido un error "+e.getMessage());
            }
        }
    }//GEN-LAST:event_RetirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetirarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetirarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetirarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetirarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetirarPersona().setVisible(true);
            }
        });
    }
    
    public boolean ValidarDatos(){
        if(!ValidarNombre()){
            NoNombre.setVisible(true);
            return false;
        }else{
            NoNombre.setVisible(false);
            if(!ValidarApellido(tApellido1.getText())){
                NoApellido1.setVisible(true);
                return false;
            }else{
                NoApellido1.setVisible(false);
                if(!ValidarApellido(tApellido2.getText())){
                    NoApellido2.setVisible(true);
                    return false;
                }else{
                    NoApellido2.setVisible(false);
                    if(!ValidarFecha(tFechaNac.getText())){
                        NoFecha.setVisible(true);
                        return false;
                    }else{
                        NoFecha.setVisible(false);
                        return true;
                    }
                }
            }
        }
    }
    
    public boolean ValidarNombre(){
        Pattern p = Pattern.compile("^[A-z]{2}([ ]?[A-z]*)*$");
         Matcher m = p.matcher(tNombre.getText());
         if(m.matches()){
             return true;
         }
         else{
             return false;
         } 
    }
    
    public boolean ValidarApellido(String apellido){
        Pattern p = Pattern.compile("^[A-z]{2,4}([ ]?[A-z]*)*$");
         Matcher m = p.matcher(apellido);
         if(m.matches()){
             return true;
         }
         else{
             return false;
         } 
    }
    
    public boolean ValidarFecha(String fechaS){
        try{
            LocalDate fecha = LocalDate.parse(fechaS,formatoFecha);
            if(fecha.isAfter(LocalDate.now())){
                NoFecha.setText("*Fecha futura");
                return false;
            }else{
                return true;
            }
        }catch(java.time.format.DateTimeParseException e){
            NoFecha.setText("*Fecha no válida (dd/mm/aaaa)");
            return false;
        }
        
    }
    
    public void PersonaNoEncontrada(){
        JOptionPane.showMessageDialog(this,"No se ha encontrado a la persona");
    }
    
    public void PersonaEncontrada(Persona p){
        pe = p;
        cbNombre = Main.RellenarComboCampamentosPersona(cbNombre,pe.getId());
        cbNombre.setEnabled(true);
        tNombre.setEnabled(false);
        Buscar.setEnabled(false);
        tApellido1.setEnabled(false);
        tApellido2.setEnabled(false);
        tFechaNac.setEnabled(false);
        Retirar.setEnabled(true);
    }
    
    public void LimpiarCampos(){
        tFechaI.setText("");
        tFechaF.setText("");
        tLugar.setText("");
    }
    
    public void setCampamentos(ArrayList<Campamento> camps){
        campamentos = camps;
    }
    
    public void PersonaRetirada(){
        JOptionPane.showMessageDialog(this, "Persona retirada de "+camp.getNombre()+" con éxito");
    }
    
    public void PersonaEliminada(){
        JOptionPane.showMessageDialog(this, "Se ha eliminado a "+pe.getNombre()+" por no estar en ningún campamento");
    }
    
    public void VerInscripciones(int op){
        opcion = op;
        titulo.setText("Ver inscripciones");
        Retirar.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel NoApellido1;
    private javax.swing.JLabel NoApellido2;
    private javax.swing.JLabel NoFecha;
    private javax.swing.JLabel NoNombre;
    private javax.swing.JButton Retirar;
    private javax.swing.JComboBox<String> cbNombre;
    private javax.swing.JLabel eApellido2;
    private javax.swing.JLabel eLugar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panelCamp;
    private javax.swing.JTextField tApellido1;
    private javax.swing.JTextField tApellido2;
    private javax.swing.JTextField tFechaF;
    private javax.swing.JTextField tFechaI;
    private javax.swing.JTextField tFechaNac;
    private javax.swing.JTextField tLugar;
    private javax.swing.JTextField tNombre;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
